spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sk?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  redis:
    database: 10
    host: localhost
    port: 6379
#  redis:
#    cluster:
#      nodes: 127.0.0.1:7000,192.168.19.88:7001
#      max-redirects: 6
#    password: aaaaaaaaaaaaaaaa
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: 10000
#        max-idle: 8

